-- Insertar los 29 nuevos procesos para Centros Deportivos
-- Mapeados a las categorías originales (A-E) para evitar saturar el catálogo principal.
INSERT INTO public.processes (
    id, codigo, categoria, categoria_nombre, nombre, tagline, recomendado, 
    descripcion_detallada, pasos, personalizacion, sectores, herramientas, dolores, landing_slug
) VALUES 
('CM1', 'CM1', 'E', 'Atención y Ventas', 'Lead capture desde web / redes sociales → CRM', 'Los leads entran solos en tu CRM y arrancan su secuencia.', true, 'Cuando alguien rellena un formulario de ''prueba gratuita'' o ''más información'' en la web o Instagram, el contacto entra automáticamente en el CRM/email marketing con etiqueta de origen y arranca una secuencia de nurturing.', '["Captura de lead desde formulario/RRSS", "Sincronización con CRM", "Activación de secuencia de email/notificación"]', 'Define los campos a capturar y el CRM de destino (HubSpot, ActiveCampaign, etc.).', ARRAY['Centros Deportivos'], ARRAY['Typeform', 'HubSpot', 'ActiveCampaign', 'Make'], ARRAY['Tienes leads de prueba gratuita que nunca nadie siguió', 'Pierdo solicitudes entre WhatsApp/Instagram/email'], 'centros-deportivos'),

('CM2', 'CM2', 'E', 'Atención y Ventas', 'Secuencia de bienvenida para leads fríos', 'No dejes que ningún lead se olvide de ti.', true, 'Tras capturar un lead que no convierte de inmediato, se activa una secuencia de 3-5 emails o WhatsApp con testimonios, beneficios y oferta de primera clase gratuita. Se detiene automáticamente si convierte.', '["Trigger por nuevo lead", "Envío de secuencia temporizada", "Detección de conversión para parada automática"]', 'Elige el canal (Email/WhatsApp) y el número de impactos.', ARRAY['Centros Deportivos'], ARRAY['ActiveCampaign', 'Brevo', 'WhatsApp Business API'], ARRAY['Tardamos en responder y perdemos clientes'], 'centros-deportivos'),

('CM3', 'CM3', 'E', 'Atención y Ventas', 'Campaña de reactivación de ex-socios', 'Recupera antiguos alumnos con ofertas personalizadas.', true, 'Segmenta automáticamente los socios que causaron baja hace más de 3 meses y les envía una oferta de reincorporación personalizada por email o WhatsApp. Se activa mensualmente o en fechas clave.', '["Filtro de ex-socios (baja > 3 meses)", "Envío de oferta vía Email/WhatsApp", "Seguimiento de respuesta"]', 'Define el tiempo de inactividad y las fechas de lanzamiento.', ARRAY['Centros Deportivos'], ARRAY['ActiveCampaign', 'Airtable', 'Mindbody', 'Make'], ARRAY['Los socios se van sin avisar y te enteras cuando ya es tarde'], 'centros-deportivos'),

('GV4', 'GV4', 'C', 'Finanzas y Tesorería', 'Notificación de renovación de cuota próxima a vencer', 'Renovaciones automáticas sin fricción.', true, '7 y 2 días antes de que venza la membresía, el socio recibe un aviso automático por email y/o WhatsApp con enlace de pago o renovación. Si no renueva, entra en flujo de retención.', '["Monitorización de fechas de vencimiento", "Avisos automáticos T-7 y T-2", "Link de pago directo"]', 'Elige los días de antelación y el tono del mensaje.', ARRAY['Centros Deportivos'], ARRAY['Make', 'WhatsApp Business API', 'Stripe'], ARRAY['Los cobros fallidos los sigues persiguiendo tú'], 'centros-deportivos'),

('GV5', 'GV5', 'C', 'Finanzas y Tesorería', 'Reactivación de leads fríos (no convirtieron tras prueba)', 'Vuelve a por los alumnos que probaron y no volvieron.', false, 'Leads que asistieron a la clase de prueba pero no se dieron de alta entran en una secuencia de reactivación automática a los 15, 30 y 60 días: email con testimonio, oferta limitada y enlace de reserva.', '["Detección de ''Prueba sin Alta''", "Secuencia 15/30/60 días", "Aviso a equipo si hay respuesta"]', 'Define los incentivos y el número de recordatorios.', ARRAY['Centros Deportivos'], ARRAY['ActiveCampaign', 'Make', 'Calendly'], ARRAY['Tienes leads de prueba gratuita que nunca nadie siguió'], 'centros-deportivos'),

('GV6', 'GV6', 'C', 'Finanzas y Tesorería', 'Programa de referidos automatizado', 'Tus alumnos son tus mejores comerciales.', false, 'A los 30 días del alta, el alumno recibe un incentivo para referir a un amigo. Si el referido se da de alta, el sistema detecta el origen y aplica el beneficio automáticamente.', '["Trigger a los 30 días del alta", "Envío de link único de referido", "Atribución automática de premio"]', 'Elige el premio (mes gratis, descuento, etc.).', ARRAY['Centros Deportivos'], ARRAY['ReferralHero', 'Viral Loops', 'Make', 'ActiveCampaign'], ARRAY['Necesito más reservas'], 'centros-deportivos'),

('GV7', 'GV7', 'C', 'Finanzas y Tesorería', 'Notificación y seguimiento de alumnos en riesgo de baja', 'Detecta el abandono antes de que ocurra.', true, 'Si un alumno no asiste en 10 días (o su frecuencia cae un 50%), el sistema genera una alerta interna y dispara un mensaje personalizado del instructor preguntando cómo está.', '["Análisis de frecuencia de asistencia", "Detección de ''riesgo de abandono''", "Mensaje preventivo personalizado"]', 'Ajusta los días de inactividad según la intensidad del centro.', ARRAY['Centros Deportivos'], ARRAY['Virtuagym', 'Mindbody', 'Make', 'WhatsApp Business API'], ARRAY['No sabes cuántos socios están en riesgo de baja ahora mismo'], 'centros-deportivos'),

('GV8', 'GV8', 'C', 'Finanzas y Tesorería', 'Upsell de equipamiento y material deportivo', 'Vende más a tus alumnos actuales.', false, 'Cuando un alumno lleva 2 meses o sube de nivel, recibe automáticamente una recomendación de equipamiento con enlace a tienda propia o afiliado. Se activa tras exámenes de grado.', '["Trigger por antigüedad o cambio de nivel", "Envío de oferta de material", "Link a tienda online"]', 'Elige qué material recomendar por cada nivel/antigüedad.', ARRAY['Centros Deportivos'], ARRAY['Make', 'ActiveCampaign', 'Shopify'], ARRAY['Quiero automatizar presupuestos y respuestas'], 'centros-deportivos'),

('GV9', 'GV9', 'C', 'Finanzas y Tesorería', 'Gestión automatizada de bonos y packs de clases', 'Control de sesiones sin errores ni Excel manuales.', false, 'Cuando un alumno compra un bono, el sistema lleva el control. Al llegar a 2 clases restantes, envía aviso automático con enlace de renovación. Si expira, entra en flujo de recuperación.', '["Conteo automático de sesiones consumidas", "Aviso de ''bono pronto a agotar''", "Link de renovación inmediata"]', 'Configura el número de clases para el aviso de renovación.', ARRAY['Centros Deportivos'], ARRAY['Make', 'Stripe', 'ActiveCampaign'], ARRAY['Gestionas las reservas y cancelaciones a mano'], 'centros-deportivos'),

('OA10', 'OA10', 'B', 'Horarios y Proyectos', 'Alta de nuevo socio → creación de ficha y accesos', 'Onboarding inmediato y sin papeleo.', true, 'Cuando se registra un nuevo socio, se crea automáticamente su ficha, se activa su acceso al torniquete o app, y se le envía email de bienvenida con normas y horarios.', '["Recepción de alta desde web/recepción", "Creación de perfil en software de gestión", "Activación de credenciales de acceso"]', 'Define el contenido del kit de bienvenida.', ARRAY['Centros Deportivos'], ARRAY['Make', 'Virtuagym', 'Mindbody', 'Gmail'], ARRAY['Necesito centralizar la información de clientes'], 'centros-deportivos'),

('OA11', 'OA11', 'B', 'Horarios y Proyectos', 'Gestión automatizada de reservas de clases', 'Tus clases llenas y el aforo bajo control.', true, 'Los socios reservan clase desde app o web. Si cancela con poco tiempo, el sistema libera la plaza, notifica al primero en lista de espera y registra la incidencia.', '["Gestión de booking online", "Control de política de cancelación", "Notificación a lista de espera automática"]', 'Personaliza el tiempo límite de cancelación.', ARRAY['Centros Deportivos'], ARRAY['Mindbody', 'Virtuagym', 'Make', 'WhatsApp Business API'], ARRAY['Gestionas las reservas y cancelaciones a mano'], 'centros-deportivos'),

('OA12', 'OA12', 'B', 'Horarios y Proyectos', 'Control de aforo y alertas de ocupación', 'Evita salas masificadas y gestiona la demanda.', false, 'Monitoriza en tiempo real el aforo. Si una clase está al 80%, activa aviso en canal interno. Si se llena, cierra la reserva y activa lista de espera automáticamente.', '["Chequeo de ocupación vs aforo máximo", "Alertas internas por alta demanda", "Cierre dinámico de reservas"]', 'Define los umbrales de alerta (80%, 90%).', ARRAY['Centros Deportivos'], ARRAY['Software de gestión', 'Make', 'Slack'], ARRAY['No sabes cuántos socios están en riesgo de baja'], 'centros-deportivos'),

('OA13', 'OA13', 'B', 'Horarios y Proyectos', 'Informe semanal de KPIs operativos', 'La salud de tu centro, cada lunes en tu móvil.', false, 'Cada lunes a las 8h se genera y envía automáticamente al director un informe con altas, bajas, asistencia por clase, ocupación media y cobros pendientes.', '["Consolidación de datos de la semana", "Generación de dashboard resumido", "Envío vía Slack/WhatsApp/Email"]', 'Elige las métricas clave para tu tipo de centro.', ARRAY['Centros Deportivos'], ARRAY['Make', 'Google Sheets', 'Slack'], ARRAY['No sabes cuántos socios están en riesgo de baja ahora mismo'], 'centros-deportivos'),

('OA14', 'OA14', 'B', 'Horarios y Proyectos', 'Gestión de incidencias de equipamiento', 'Tus máquinas siempre a punto, sin olvidos.', false, 'Reporte de averías mediante formulario o mensaje. Se crea automáticamente un ticket, se notifica al responsable de mantenimiento y se hace seguimiento hasta resolución.', '["Entrada de incidencia desde staff", "Alta en gestor de mantenimiento", "Aviso y tracking de reparación"]', 'Elige la herramienta de tickets (ClickUp, Notion, Slack).', ARRAY['Centros Deportivos'], ARRAY['Typeform', 'Slack', 'ClickUp', 'Make'], ARRAY['Pierdo solicitudes entre WhatsApp/Instagram/email'], 'centros-deportivos'),

('OA15', 'OA15', 'B', 'Horarios y Proyectos', 'Gestión del calendario de exámenes de grado', 'Organiza tus pasos de grado sin caos administrativo.', true, 'Identifica automáticamente a los alumnos que cumplen requisitos para examen, les envía invitación con fecha y formulario de confirmación. El instructor recibe el listado 48h antes.', '["Filtrado de alumnos elegibles", "Envío masivo de invitaciones", "Consolidación de confirmaciones"]', 'Ajusta los requisitos por cada nivel o cinturón.', ARRAY['Centros Deportivos'], ARRAY['Make', 'Google Sheets', 'Gmail', 'WhatsApp Business API'], ARRAY['Quiero ordenar tareas y que se asignen solas'], 'centros-deportivos'),

('OA16', 'OA16', 'B', 'Horarios y Proyectos', 'Registro y seguimiento de lesiones de alumnos', 'Cuida a tus alumnos y evita bajas por lesiones.', false, 'Cuando un alumno reporta una lesión, se crea un registro y se genera alerta al instructor. Se adapta su ficha de reservas y se programa seguimiento a los 7 días.', '["Reporte de lesión", "Alerta automática a instructores", "Programación de check-up de salud"]', 'Define los tipos de lesiones y el protocolo de seguimiento.', ARRAY['Centros Deportivos'], ARRAY['Typeform', 'Make', 'Airtable', 'Gmail'], ARRAY['Los socios se van sin avisar'], 'centros-deportivos'),

('OA17', 'OA17', 'B', 'Horarios y Proyectos', 'Gestión de contratos y documentación firmada digitalmente', 'Cero papeles. Cero archivos físicos.', true, 'Envío automático de contratos de membresía, consentimiento informado y normas del centro para firma digital. El documento queda archivado automáticamente.', '["Generación de contrato dinámico", "Envío para firma digital", "Archivo automático en la nube"]', 'Incluye tus propias plantillas de contrato.', ARRAY['Centros Deportivos'], ARRAY['Docusign', 'SignNow', 'Make', 'Google Drive'], ARRAY['Necesito centralizar la información de clientes'], 'centros-deportivos'),

('OA18', 'OA18', 'E', 'Atención y Ventas', 'Automatización de la comunicación con padres (alumnos menores)', 'Tranquilidad total para los padres, ahorro de tiempo para ti.', true, 'Confirmación de asistencia tras cada clase, aviso si el alumno no aparece a una clase reservada y recordatorios de pagos en un canal separado del alumno.', '["Segmentación Alumno vs Tutor", "Alertas de asistencia en tiempo real", "Recordatorios de eventos infantiles"]', 'Elige qué avisos enviar a los padres y por qué canal.', ARRAY['Centros Deportivos'], ARRAY['Make', 'WhatsApp Business API', 'ActiveCampaign'], ARRAY['Tardamos en responder y perdemos clientes'], 'centros-deportivos'),

('OA19', 'OA19', 'B', 'Horarios y Proyectos', 'Informe mensual de progreso por alumno', 'Gamifica la experiencia y mejora la retención.', true, 'Resumen de actividad mensual: clases asistidas, racha, próximo examen estimado y mensaje personalizado del instructor para aumentar el compromiso.', '["Agregación de actividad mensual", "Generación de reporte visual", "Envío personalizado automatizado"]', 'Define qué hitos celebrar (ej. ''10 clases este mes'').', ARRAY['Centros Deportivos'], ARRAY['Make', 'Software de gestión', 'ActiveCampaign', 'Google Sheets'], ARRAY['Los socios se van sin avisar'], 'centros-deportivos'),

('AC20', 'AC20', 'E', 'Atención y Ventas', 'Respuesta automática a consultas frecuentes por WhatsApp', 'Tu recepción abierta 24/7 sin contratar a nadie.', true, 'Un bot de WhatsApp responde automáticamente a preguntas sobre horarios, precios o cómo darse de alta. Escala a recepción si la duda requiere intervención humana.', '["Detección de intención (NLP)", "Respuesta desde base de conocimiento", "Escalado inteligente con contexto"]', 'Entrena al bot con tus horarios y tarifas específicas.', ARRAY['Centros Deportivos'], ARRAY['WhatsApp Business API', 'Make', 'ChatGPT'], ARRAY['Me escriben mucho y no doy abasto', 'Tengo muchas preguntas repetidas'], 'centros-deportivos'),

('AC21', 'AC21', 'E', 'Atención y Ventas', 'Encuesta de satisfacción post-clase', 'Escucha a tus alumnos en caliente.', false, '2 horas después de la clase, el asistente recibe una encuesta de 1-2 preguntas. Las valoraciones bajas generan una alerta inmediata al responsable.', '["Trigger post-asistencia", "Envío de micro-encuesta", "Alertas por malas valoraciones"]', 'Elige las preguntas y el tiempo de espera post-clase.', ARRAY['Centros Deportivos'], ARRAY['Typeform', 'Make', 'ActiveCampaign'], ARRAY['Los socios se van sin avisar'], 'centros-deportivos'),

('AC22', 'AC22', 'E', 'Atención y Ventas', 'Gestión de quejas y reclamaciones', 'Atiende los problemas antes de que se conviertan en bajas.', false, 'Al enviar una queja, se crea automáticamente un ticket, se confirma recepción y se asigna con SLA de respuesta definido (ej: 24h).', '["Captura de queja vía formulario", "Creación de ticket prioritario", "Notificación y seguimiento de SLA"]', 'Define tus tiempos de respuesta por tipo de queja.', ARRAY['Centros Deportivos'], ARRAY['Typeform', 'ClickUp', 'Make'], ARRAY['Los socios se van sin avisar'], 'centros-deportivos'),

('AC23', 'AC23', 'E', 'Atención y Ventas', 'Felicitación de cumpleaños con oferta', 'Fideliza a través de los pequeños detalles.', false, 'El día de su cumpleaños el socio recibe un mensaje personalizado por WhatsApp o email con una oferta especial (ej. sesión de entrenamiento gratis).', '["Trigger por fecha de natalicio", "Envío de mensaje festivo", "Inclusión de cupón/oferta"]', 'Elige qué regalo hacer a cada tipo de socio.', ARRAY['Centros Deportivos'], ARRAY['ActiveCampaign', 'Make', 'WhatsApp Business API'], ARRAY['Los socios se van sin avisar'], 'centros-deportivos'),

('AC24', 'AC24', 'E', 'Atención y Ventas', 'Detección de socios en riesgo de baja (churn)', 'Reactiva a los alumnos ausentes antes de perderlos.', true, 'Si un socio no asiste en 14 días, entra en flujo de reactivación: mensaje de ¿todo bien?, oferta de sesión de reenganche y alerta al equipo.', '["Chequeo diario de inactividad", "Multicanalidad de contacto (Email/WA)", "Oferta de rescate personalizada"]', 'Define el umbral de ''riesgo'' (14, 20 o 30 días).', ARRAY['Centros Deportivos'], ARRAY['Software de gestión', 'Make', 'ActiveCampaign', 'WhatsApp'], ARRAY['No sabes cuántos socios están en riesgo de baja ahora mismo'], 'centros-deportivos'),

('RO25', 'RO25', 'D', 'Internos Agencias', 'Onboarding de nuevo empleado / entrenador / alumno', 'Experiencia premium desde el minuto 1.', false, 'Checklist automático de onboarding: envío de documentación, acceso a herramientas, asignación de mentor y recordatorios de pasos pendientes.', '["Lanzamiento de workflow por nuevo contrato", "Distribución de kit de bienvenida digital", "Seguimiento de tareas de onboarding"]', 'Adapta el checklist por rol (staff, instructor, alumno).', ARRAY['Centros Deportivos'], ARRAY['Make', 'Notion', 'Gmail'], ARRAY['Quiero ordenar tareas y que se asignen solas'], 'centros-deportivos'),

('RO26', 'RO26', 'D', 'Internos Agencias', 'Gestión de turnos y disponibilidad de instructores', 'Horarios sin conflictos y sin llamadas constantes.', false, 'Los instructores informan disponibilidad vía formulario. El sistema cruza con la programación, detecta conflictos y notifica huecos sin cubrir.', '["Recogida de disponibilidad semanal", "Cruce automático con calendario de clases", "Notificación de incidencias de cobertura"]', 'Define los plazos para informar la disponibilidad.', ARRAY['Centros Deportivos'], ARRAY['Typeform', 'Make', 'Google Calendar', 'Slack'], ARRAY['Quiero ordenar tareas y que se asignen solas'], 'centros-deportivos'),

('FF27', 'FF27', 'C', 'Finanzas y Tesorería', 'Cobro recurrente y gestión de impagos', 'Asegura tus ingresos sin perseguir recibos.', true, 'Procesamiento automático de cobros. Si falla, el sistema reintenta a los 3 días, notifica al socio con link de pago y alerta a administración.', '["Ejecución de remesa/cobro tarjeta", "Lógica de reintentos automática", "Comunicación de deuda instantánea"]', 'Define el número de reintentos y los plazos de aviso.', ARRAY['Centros Deportivos'], ARRAY['Stripe', 'GoCardless', 'Make', 'WhatsApp Business API'], ARRAY['Los cobros fallidos los sigues persiguiendo tú'], 'centros-deportivos'),

('FF28', 'FF28', 'C', 'Finanzas y Tesorería', 'Alerta de pagos pendientes a proveedores', 'Control de gastos bajo control.', false, 'Revisión semanal de facturas de proveedores (mantenimiento, suministros) y alerta al responsable con los vencimientos próximos.', '["Lectura de fechas de vencimiento de compra", "Consolidación semanal de pagos", "Avisos internos de tesorería"]', 'Elige el día de la semana para el resumen de pagos.', ARRAY['Centros Deportivos'], ARRAY['Airtable', 'Make', 'Gmail'], ARRAY['Necesito centralizar la información de clientes'], 'centros-deportivos'),

('OE29', 'OE29', 'B', 'Horarios y Proyectos', 'Programación y comunicación de cambios en horario de clases', 'Avisa de imprevistos al instante y sin caos.', true, 'Si se modifica o cancela una clase, el sistema notifica automáticamente a los socios con reserva, ofrece alternativas y actualiza el calendario público.', '["Actualización de horario en sistema", "Identificación de socios afectados", "Aviso masivo multicanal"]', 'Define el margen de tiempo para avisar de cancelaciones.', ARRAY['Centros Deportivos'], ARRAY['Software de gestión', 'Make', 'WhatsApp Business API'], ARRAY['Gestionas las reservas y cancelaciones a mano'], 'centros-deportivos')

ON CONFLICT (id) DO UPDATE SET
    codigo = EXCLUDED.codigo,
    categoria = EXCLUDED.categoria,
    categoria_nombre = EXCLUDED.categoria_nombre,
    nombre = EXCLUDED.nombre,
    tagline = EXCLUDED.tagline,
    recomendado = EXCLUDED.recomendado,
    descripcion_detallada = EXCLUDED.descripcion_detallada,
    pasos = EXCLUDED.pasos,
    personalizacion = EXCLUDED.personalizacion,
    sectores = EXCLUDED.sectores,
    herramientas = EXCLUDED.herramientas,
    dolores = EXCLUDED.dolores,
    landing_slug = EXCLUDED.landing_slug;
